// <auto-generated />
using Category.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Category.API.Migrations
{
    [DbContext(typeof(CategoryContext))]
    [Migration("20250505162619_AddLengthConstraintForName")]
    partial class AddLengthConstraintForName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Category.API.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasCheckConstraint("CK_Category_Name_Length", "LEN([Name])>=3 AND LEN([Name])<30");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tires"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Oil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accumulators"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
